# Generated by Django 5.1.1 on 2024-10-17 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accueil', '0002_people_password_persouser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PersoUser',
        ),
    ]
