# Generated by Django 5.1.1 on 2024-10-20 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accueil', '0004_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='last_login',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
