# Generated by Django 5.1.1 on 2024-10-21 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accueil', '0007_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='cover_letter',
            field=models.FileField(upload_to='cover_letters/'),
        ),
    ]
