# Generated by Django 5.1.1 on 2024-10-21 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accueil', '0008_alter_application_cover_letter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='cover_letter',
        ),
        migrations.AddField(
            model_name='application',
            name='cover_letter_file',
            field=models.FileField(blank=True, null=True, upload_to='cover_letters/'),
        ),
    ]
